apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: messaging
  namespace: manuela-stormshift-messaging
spec:
  lookupPolicy:
    local: true
  tags:
  - name: 0.3.2-39
    from:
      kind: DockerImage
      name: quay.io/nstephan/iot-consumer:0.3.2-39
    importPolicy: {}
    referencePolicy:
      type: Local
