global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: stencell
    username: stencell
    email: nate@redhat.com
    dev_revision: main

  quay:
    provider: quay.io
    account: nstephan

  datacenter:
    clustername: sten2
    # clustername: cluster-5j96l
    domain: sandbox1022.opentlc.com
    # domain: 5j96l.sandbox650.opentlc.com

  edge:
    clustername: PLAINTEXT
    domain: PLAINTEXT
