apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-to-s3-config
  namespace: manuela-data-lake-central-s3-store
data:
  application.properties: |
    
    kafka.broker.uri=manuela-kafka-cluster-kafka-bootstrap.manuela-tst-all.svc:9092
    kafka.broker.topic.temperature=iot-sensor-sw-temperature
    kafka.broker.topic.vibration=iot-sensor-sw-vibration

    s3.region={{ .Values.s3.bucket.region }}
    s3.bucket.name={{ .Values.s3.bucket.name }}
    s3.message.aggregation.count={{ .Values.s3.bucket.message.aggregation.count }}
    s3.custom.endpoint.enabled={{ .Values.s3.bucket.custom.endpoint.enabled }}
    # Convert this directory into a helm chart and use templating to set this
    s3.custom.endpoint.url=s3-openshift-storage.apps.{{ .Values.global.datacenter.clustername }}.{{ .Values.global.datacenter.domain }}

    
